/*
 * Copyright © Siemens 2020 - 2026. ALL RIGHTS RESERVED.
 * Licensed under the MIT license
 * See LICENSE file in the top-level directory
 */

//
// Copyright © Siemens 2020 - 2026. ALL RIGHTS RESERVED.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.6
// source: Network.proto

package siemens_iedge_dmapi_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interface_InterfaceTypeEnum int32

const (
	Interface_ETHERNET Interface_InterfaceTypeEnum = 0
	Interface_GSM      Interface_InterfaceTypeEnum = 1
)

// Enum value maps for Interface_InterfaceTypeEnum.
var (
	Interface_InterfaceTypeEnum_name = map[int32]string{
		0: "ETHERNET",
		1: "GSM",
	}
	Interface_InterfaceTypeEnum_value = map[string]int32{
		"ETHERNET": 0,
		"GSM":      1,
	}
)

func (x Interface_InterfaceTypeEnum) Enum() *Interface_InterfaceTypeEnum {
	p := new(Interface_InterfaceTypeEnum)
	*p = x
	return p
}

func (x Interface_InterfaceTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interface_InterfaceTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_Network_proto_enumTypes[0].Descriptor()
}

func (Interface_InterfaceTypeEnum) Type() protoreflect.EnumType {
	return &file_Network_proto_enumTypes[0]
}

func (x Interface_InterfaceTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interface_InterfaceTypeEnum.Descriptor instead.
func (Interface_InterfaceTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 0}
}

type ConnectionSettings_ConnectionType int32

const (
	ConnectionSettings_UNKNOWN ConnectionSettings_ConnectionType = 0 // Unspecified
	ConnectionSettings_GSM     ConnectionSettings_ConnectionType = 1 // GSM-type connections
)

// Enum value maps for ConnectionSettings_ConnectionType.
var (
	ConnectionSettings_ConnectionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GSM",
	}
	ConnectionSettings_ConnectionType_value = map[string]int32{
		"UNKNOWN": 0,
		"GSM":     1,
	}
)

func (x ConnectionSettings_ConnectionType) Enum() *ConnectionSettings_ConnectionType {
	p := new(ConnectionSettings_ConnectionType)
	*p = x
	return p
}

func (x ConnectionSettings_ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionSettings_ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_Network_proto_enumTypes[1].Descriptor()
}

func (ConnectionSettings_ConnectionType) Type() protoreflect.EnumType {
	return &file_Network_proto_enumTypes[1]
}

func (x ConnectionSettings_ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionSettings_ConnectionType.Descriptor instead.
func (ConnectionSettings_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{3, 0}
}

// Contains MAC address, used for retrieving specified Network Interface settings.
type NetworkInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceRequest) Reset() {
	*x = NetworkInterfaceRequest{}
	mi := &file_Network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceRequest) ProtoMessage() {}

func (x *NetworkInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceRequest.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkInterfaceRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

// Returns an Network Interface with
type NetworkInterfaceRequestWithLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceRequestWithLabel) Reset() {
	*x = NetworkInterfaceRequestWithLabel{}
	mi := &file_Network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceRequestWithLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceRequestWithLabel) ProtoMessage() {}

func (x *NetworkInterfaceRequestWithLabel) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceRequestWithLabel.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceRequestWithLabel) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterfaceRequestWithLabel) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Interface type holds settings for a Network Interface.
type Interface struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	GatewayInterface bool                         `protobuf:"varint,1,opt,name=GatewayInterface,proto3" json:"GatewayInterface,omitempty"` // if true, route metric will be set to 1. Otherwise route metric is -1. Similarly, when the interface is requested,return value will be true if route metric is 1.
	MacAddress       string                       `protobuf:"bytes,2,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`              // "20:87:56:b5:ed:e0"
	DHCP             string                       `protobuf:"bytes,3,opt,name=DHCP,proto3" json:"DHCP,omitempty"`                          // values can be 'enabled' or 'disabled'. for compatiblity reasons it is not boolean.
	Static           *Interface_StaticConf        `protobuf:"bytes,4,opt,name=Static,proto3" json:"Static,omitempty"`                      // Static field is StaticConf type instance.
	DNSConfig        *Interface_Dns               `protobuf:"bytes,5,opt,name=DNSConfig,proto3" json:"DNSConfig,omitempty"`                // DNSConfig is dns type instance.
	L2Conf           *Interface_L2                `protobuf:"bytes,6,opt,name=L2Conf,proto3" json:"L2Conf,omitempty"`
	InterfaceName    string                       `protobuf:"bytes,7,opt,name=InterfaceName,proto3" json:"InterfaceName,omitempty"` // ens2p
	Label            string                       `protobuf:"bytes,8,opt,name=Label,proto3" json:"Label,omitempty"`                 // x1
	Routes           []*Interface_Route           `protobuf:"bytes,9,rep,name=Routes,proto3" json:"Routes,omitempty"`               // a list of routes for the interface.
	InterfaceType    *Interface_InterfaceTypeEnum `protobuf:"varint,10,opt,name=InterfaceType,proto3,enum=siemens.iedge.dmapi.network.v1.Interface_InterfaceTypeEnum,oneof" json:"InterfaceType,omitempty"`
	GsmConfiguration *Interface_GsmConf           `protobuf:"bytes,11,opt,name=GsmConfiguration,proto3" json:"GsmConfiguration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_Network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2}
}

func (x *Interface) GetGatewayInterface() bool {
	if x != nil {
		return x.GatewayInterface
	}
	return false
}

func (x *Interface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Interface) GetDHCP() string {
	if x != nil {
		return x.DHCP
	}
	return ""
}

func (x *Interface) GetStatic() *Interface_StaticConf {
	if x != nil {
		return x.Static
	}
	return nil
}

func (x *Interface) GetDNSConfig() *Interface_Dns {
	if x != nil {
		return x.DNSConfig
	}
	return nil
}

func (x *Interface) GetL2Conf() *Interface_L2 {
	if x != nil {
		return x.L2Conf
	}
	return nil
}

func (x *Interface) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Interface) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Interface) GetRoutes() []*Interface_Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Interface) GetInterfaceType() Interface_InterfaceTypeEnum {
	if x != nil && x.InterfaceType != nil {
		return *x.InterfaceType
	}
	return Interface_ETHERNET
}

func (x *Interface) GetGsmConfiguration() *Interface_GsmConf {
	if x != nil {
		return x.GsmConfiguration
	}
	return nil
}

type ConnectionSettings struct {
	state          protoimpl.MessageState            `protogen:"open.v1"`
	Name           string                            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Connection name, e.g.: "Cellular Connection 1"
	ConnectionType ConnectionSettings_ConnectionType `protobuf:"varint,2,opt,name=connection_type,json=connectionType,proto3,enum=siemens.iedge.dmapi.network.v1.ConnectionSettings_ConnectionType" json:"connection_type,omitempty"`
	// Types that are valid to be assigned to ConnectionConfig:
	//
	//	*ConnectionSettings_Gsm
	ConnectionConfig isConnectionSettings_ConnectionConfig `protobuf_oneof:"connection_config"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionSettings) Reset() {
	*x = ConnectionSettings{}
	mi := &file_Network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSettings) ProtoMessage() {}

func (x *ConnectionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSettings.ProtoReflect.Descriptor instead.
func (*ConnectionSettings) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionSettings) GetConnectionType() ConnectionSettings_ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return ConnectionSettings_UNKNOWN
}

func (x *ConnectionSettings) GetConnectionConfig() isConnectionSettings_ConnectionConfig {
	if x != nil {
		return x.ConnectionConfig
	}
	return nil
}

func (x *ConnectionSettings) GetGsm() *Interface_GsmConf {
	if x != nil {
		if x, ok := x.ConnectionConfig.(*ConnectionSettings_Gsm); ok {
			return x.Gsm
		}
	}
	return nil
}

type isConnectionSettings_ConnectionConfig interface {
	isConnectionSettings_ConnectionConfig()
}

type ConnectionSettings_Gsm struct {
	Gsm *Interface_GsmConf `protobuf:"bytes,3,opt,name=gsm,proto3,oneof"` // <-- Reusing GsmConf from Interface
}

func (*ConnectionSettings_Gsm) isConnectionSettings_ConnectionConfig() {}

// Contains multiple network interface settings. It can be used to apply or get the settings.
type NetworkSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*Interface           `protobuf:"bytes,1,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`                                                                       // Network settings contains an array of Interfaces.Applying new settings or receiving current settings is supported for multiple ethernet typed network interfaces supported.
	LabelMap      map[string]string      `protobuf:"bytes,2,rep,name=LabelMap,proto3" json:"LabelMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // LabelMap contains port label and corresponding interface-name. e.g key : x1 value: enp2s0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSettings) Reset() {
	*x = NetworkSettings{}
	mi := &file_Network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSettings) ProtoMessage() {}

func (x *NetworkSettings) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSettings.ProtoReflect.Descriptor instead.
func (*NetworkSettings) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkSettings) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkSettings) GetLabelMap() map[string]string {
	if x != nil {
		return x.LabelMap
	}
	return nil
}

// StaticConf type holds IP Netmask and Gateway information
type Interface_StaticConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv4          string                 `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`       // e.g: 192.168.0.2
	NetMask       string                 `protobuf:"bytes,2,opt,name=NetMask,proto3" json:"NetMask,omitempty"` // e.g: 255.255.255.0
	Gateway       string                 `protobuf:"bytes,3,opt,name=Gateway,proto3" json:"Gateway,omitempty"` // e.g: 192.168.0.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface_StaticConf) Reset() {
	*x = Interface_StaticConf{}
	mi := &file_Network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface_StaticConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface_StaticConf) ProtoMessage() {}

func (x *Interface_StaticConf) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface_StaticConf.ProtoReflect.Descriptor instead.
func (*Interface_StaticConf) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Interface_StaticConf) GetIPv4() string {
	if x != nil {
		return x.IPv4
	}
	return ""
}

func (x *Interface_StaticConf) GetNetMask() string {
	if x != nil {
		return x.NetMask
	}
	return ""
}

func (x *Interface_StaticConf) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

// Type that contains Primary and Secondary DNS.
type Interface_Dns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryDNS    string                 `protobuf:"bytes,1,opt,name=PrimaryDNS,proto3" json:"PrimaryDNS,omitempty"`     // e.g:  "1.1.1.2"
	SecondaryDNS  string                 `protobuf:"bytes,2,opt,name=SecondaryDNS,proto3" json:"SecondaryDNS,omitempty"` // e.g: "1.1.1.1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface_Dns) Reset() {
	*x = Interface_Dns{}
	mi := &file_Network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface_Dns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface_Dns) ProtoMessage() {}

func (x *Interface_Dns) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface_Dns.ProtoReflect.Descriptor instead.
func (*Interface_Dns) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Interface_Dns) GetPrimaryDNS() string {
	if x != nil {
		return x.PrimaryDNS
	}
	return ""
}

func (x *Interface_Dns) GetSecondaryDNS() string {
	if x != nil {
		return x.SecondaryDNS
	}
	return ""
}

type Interface_L2 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StartingAddressIPv4 string                 `protobuf:"bytes,1,opt,name=StartingAddressIPv4,proto3" json:"StartingAddressIPv4,omitempty"`                                                                         // e.g: 192.168.0.2
	NetMask             string                 `protobuf:"bytes,2,opt,name=NetMask,proto3" json:"NetMask,omitempty"`                                                                                                 // e.g: 255.255.255.0
	Range               string                 `protobuf:"bytes,3,opt,name=Range,proto3" json:"Range,omitempty"`                                                                                                     // e.g: 16
	Gateway             string                 `protobuf:"bytes,4,opt,name=Gateway,proto3" json:"Gateway,omitempty"`                                                                                                 //e.g: 192.168.2.1
	AuxiliaryAddresses  map[string]string      `protobuf:"bytes,5,rep,name=AuxiliaryAddresses,proto3" json:"AuxiliaryAddresses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //Preserved addresses for other devices. These addresses won't be assigned to containers. e.g  my_plc,  192.168.0.5
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Interface_L2) Reset() {
	*x = Interface_L2{}
	mi := &file_Network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface_L2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface_L2) ProtoMessage() {}

func (x *Interface_L2) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface_L2.ProtoReflect.Descriptor instead.
func (*Interface_L2) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Interface_L2) GetStartingAddressIPv4() string {
	if x != nil {
		return x.StartingAddressIPv4
	}
	return ""
}

func (x *Interface_L2) GetNetMask() string {
	if x != nil {
		return x.NetMask
	}
	return ""
}

func (x *Interface_L2) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *Interface_L2) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Interface_L2) GetAuxiliaryAddresses() map[string]string {
	if x != nil {
		return x.AuxiliaryAddresses
	}
	return nil
}

type Interface_Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=Destination,proto3" json:"Destination,omitempty"` // Required. Dotted decimal IP address, e.g: 192.168.5.0
	Netmask       string                 `protobuf:"bytes,2,opt,name=Netmask,proto3" json:"Netmask,omitempty"`         // Required. Netmask formatted as dotted decimal IP address, e.g.: 255.255.255.0
	NextHop       string                 `protobuf:"bytes,3,opt,name=NextHop,proto3" json:"NextHop,omitempty"`         // Optional. Dotted decimal gateway IP address, e.g.: 10.0.1.5. If not specified, the route will not have a gateway defined.
	Metric        uint32                 `protobuf:"varint,4,opt,name=Metric,proto3" json:"Metric,omitempty"`          // Required. Route metric within range [2-4294967295] (inclusive), e.g: 2 or 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface_Route) Reset() {
	*x = Interface_Route{}
	mi := &file_Network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface_Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface_Route) ProtoMessage() {}

func (x *Interface_Route) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface_Route.ProtoReflect.Descriptor instead.
func (*Interface_Route) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Interface_Route) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Interface_Route) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *Interface_Route) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *Interface_Route) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

type Interface_GsmConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apn           string                 `protobuf:"bytes,1,opt,name=Apn,proto3" json:"Apn,omitempty"`           // Required. Access Point Name, e.g.: "internet"
	Pin           string                 `protobuf:"bytes,2,opt,name=Pin,proto3" json:"Pin,omitempty"`           // Optional. SIM card PIN
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"` // Optional. APN Username for authentication
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"` // Optional. APN Password for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface_GsmConf) Reset() {
	*x = Interface_GsmConf{}
	mi := &file_Network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface_GsmConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface_GsmConf) ProtoMessage() {}

func (x *Interface_GsmConf) ProtoReflect() protoreflect.Message {
	mi := &file_Network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface_GsmConf.ProtoReflect.Descriptor instead.
func (*Interface_GsmConf) Descriptor() ([]byte, []int) {
	return file_Network_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Interface_GsmConf) GetApn() string {
	if x != nil {
		return x.Apn
	}
	return ""
}

func (x *Interface_GsmConf) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Interface_GsmConf) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Interface_GsmConf) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_Network_proto protoreflect.FileDescriptor

const file_Network_proto_rawDesc = "" +
	"\n" +
	"\rNetwork.proto\x12\x1esiemens.iedge.dmapi.network.v1\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x17NetworkInterfaceRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\"8\n" +
	" NetworkInterfaceRequestWithLabel\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"\x95\v\n" +
	"\tInterface\x12*\n" +
	"\x10GatewayInterface\x18\x01 \x01(\bR\x10GatewayInterface\x12\x1e\n" +
	"\n" +
	"MacAddress\x18\x02 \x01(\tR\n" +
	"MacAddress\x12\x12\n" +
	"\x04DHCP\x18\x03 \x01(\tR\x04DHCP\x12L\n" +
	"\x06Static\x18\x04 \x01(\v24.siemens.iedge.dmapi.network.v1.Interface.StaticConfR\x06Static\x12K\n" +
	"\tDNSConfig\x18\x05 \x01(\v2-.siemens.iedge.dmapi.network.v1.Interface.DnsR\tDNSConfig\x12D\n" +
	"\x06L2Conf\x18\x06 \x01(\v2,.siemens.iedge.dmapi.network.v1.Interface.L2R\x06L2Conf\x12$\n" +
	"\rInterfaceName\x18\a \x01(\tR\rInterfaceName\x12\x14\n" +
	"\x05Label\x18\b \x01(\tR\x05Label\x12G\n" +
	"\x06Routes\x18\t \x03(\v2/.siemens.iedge.dmapi.network.v1.Interface.RouteR\x06Routes\x12f\n" +
	"\rInterfaceType\x18\n" +
	" \x01(\x0e2;.siemens.iedge.dmapi.network.v1.Interface.InterfaceTypeEnumH\x00R\rInterfaceType\x88\x01\x01\x12]\n" +
	"\x10GsmConfiguration\x18\v \x01(\v21.siemens.iedge.dmapi.network.v1.Interface.GsmConfR\x10GsmConfiguration\x1aT\n" +
	"\n" +
	"StaticConf\x12\x12\n" +
	"\x04IPv4\x18\x01 \x01(\tR\x04IPv4\x12\x18\n" +
	"\aNetMask\x18\x02 \x01(\tR\aNetMask\x12\x18\n" +
	"\aGateway\x18\x03 \x01(\tR\aGateway\x1aI\n" +
	"\x03Dns\x12\x1e\n" +
	"\n" +
	"PrimaryDNS\x18\x01 \x01(\tR\n" +
	"PrimaryDNS\x12\"\n" +
	"\fSecondaryDNS\x18\x02 \x01(\tR\fSecondaryDNS\x1a\xbd\x02\n" +
	"\x02L2\x120\n" +
	"\x13StartingAddressIPv4\x18\x01 \x01(\tR\x13StartingAddressIPv4\x12\x18\n" +
	"\aNetMask\x18\x02 \x01(\tR\aNetMask\x12\x14\n" +
	"\x05Range\x18\x03 \x01(\tR\x05Range\x12\x18\n" +
	"\aGateway\x18\x04 \x01(\tR\aGateway\x12t\n" +
	"\x12AuxiliaryAddresses\x18\x05 \x03(\v2D.siemens.iedge.dmapi.network.v1.Interface.L2.AuxiliaryAddressesEntryR\x12AuxiliaryAddresses\x1aE\n" +
	"\x17AuxiliaryAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1au\n" +
	"\x05Route\x12 \n" +
	"\vDestination\x18\x01 \x01(\tR\vDestination\x12\x18\n" +
	"\aNetmask\x18\x02 \x01(\tR\aNetmask\x12\x18\n" +
	"\aNextHop\x18\x03 \x01(\tR\aNextHop\x12\x16\n" +
	"\x06Metric\x18\x04 \x01(\rR\x06Metric\x1ae\n" +
	"\aGsmConf\x12\x10\n" +
	"\x03Apn\x18\x01 \x01(\tR\x03Apn\x12\x10\n" +
	"\x03Pin\x18\x02 \x01(\tR\x03Pin\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\"*\n" +
	"\x11InterfaceTypeEnum\x12\f\n" +
	"\bETHERNET\x10\x00\x12\a\n" +
	"\x03GSM\x10\x01B\x10\n" +
	"\x0e_InterfaceType\"\x98\x02\n" +
	"\x12ConnectionSettings\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12j\n" +
	"\x0fconnection_type\x18\x02 \x01(\x0e2A.siemens.iedge.dmapi.network.v1.ConnectionSettings.ConnectionTypeR\x0econnectionType\x12E\n" +
	"\x03gsm\x18\x03 \x01(\v21.siemens.iedge.dmapi.network.v1.Interface.GsmConfH\x00R\x03gsm\"&\n" +
	"\x0eConnectionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03GSM\x10\x01B\x13\n" +
	"\x11connection_config\"\xf4\x01\n" +
	"\x0fNetworkSettings\x12I\n" +
	"\n" +
	"Interfaces\x18\x01 \x03(\v2).siemens.iedge.dmapi.network.v1.InterfaceR\n" +
	"Interfaces\x12Y\n" +
	"\bLabelMap\x18\x02 \x03(\v2=.siemens.iedge.dmapi.network.v1.NetworkSettings.LabelMapEntryR\bLabelMap\x1a;\n" +
	"\rLabelMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x89\x05\n" +
	"\x0eNetworkService\x12[\n" +
	"\x10GetAllInterfaces\x12\x16.google.protobuf.Empty\x1a/.siemens.iedge.dmapi.network.v1.NetworkSettings\x12y\n" +
	"\x13GetInterfaceWithMac\x127.siemens.iedge.dmapi.network.v1.NetworkInterfaceRequest\x1a).siemens.iedge.dmapi.network.v1.Interface\x12\x84\x01\n" +
	"\x15GetInterfaceWithLabel\x12@.siemens.iedge.dmapi.network.v1.NetworkInterfaceRequestWithLabel\x1a).siemens.iedge.dmapi.network.v1.Interface\x12X\n" +
	"\rApplySettings\x12/.siemens.iedge.dmapi.network.v1.NetworkSettings\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x10CreateConnection\x122.siemens.iedge.dmapi.network.v1.ConnectionSettings\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x10RemoveConnection\x122.siemens.iedge.dmapi.network.v1.ConnectionSettings\x1a\x16.google.protobuf.EmptyB\x1aZ\x18.;siemens_iedge_dmapi_v1b\x06proto3"

var (
	file_Network_proto_rawDescOnce sync.Once
	file_Network_proto_rawDescData []byte
)

func file_Network_proto_rawDescGZIP() []byte {
	file_Network_proto_rawDescOnce.Do(func() {
		file_Network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Network_proto_rawDesc), len(file_Network_proto_rawDesc)))
	})
	return file_Network_proto_rawDescData
}

var file_Network_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Network_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_Network_proto_goTypes = []any{
	(Interface_InterfaceTypeEnum)(0),         // 0: siemens.iedge.dmapi.network.v1.Interface.InterfaceTypeEnum
	(ConnectionSettings_ConnectionType)(0),   // 1: siemens.iedge.dmapi.network.v1.ConnectionSettings.ConnectionType
	(*NetworkInterfaceRequest)(nil),          // 2: siemens.iedge.dmapi.network.v1.NetworkInterfaceRequest
	(*NetworkInterfaceRequestWithLabel)(nil), // 3: siemens.iedge.dmapi.network.v1.NetworkInterfaceRequestWithLabel
	(*Interface)(nil),                        // 4: siemens.iedge.dmapi.network.v1.Interface
	(*ConnectionSettings)(nil),               // 5: siemens.iedge.dmapi.network.v1.ConnectionSettings
	(*NetworkSettings)(nil),                  // 6: siemens.iedge.dmapi.network.v1.NetworkSettings
	(*Interface_StaticConf)(nil),             // 7: siemens.iedge.dmapi.network.v1.Interface.StaticConf
	(*Interface_Dns)(nil),                    // 8: siemens.iedge.dmapi.network.v1.Interface.Dns
	(*Interface_L2)(nil),                     // 9: siemens.iedge.dmapi.network.v1.Interface.L2
	(*Interface_Route)(nil),                  // 10: siemens.iedge.dmapi.network.v1.Interface.Route
	(*Interface_GsmConf)(nil),                // 11: siemens.iedge.dmapi.network.v1.Interface.GsmConf
	nil,                                      // 12: siemens.iedge.dmapi.network.v1.Interface.L2.AuxiliaryAddressesEntry
	nil,                                      // 13: siemens.iedge.dmapi.network.v1.NetworkSettings.LabelMapEntry
	(*emptypb.Empty)(nil),                    // 14: google.protobuf.Empty
}
var file_Network_proto_depIdxs = []int32{
	7,  // 0: siemens.iedge.dmapi.network.v1.Interface.Static:type_name -> siemens.iedge.dmapi.network.v1.Interface.StaticConf
	8,  // 1: siemens.iedge.dmapi.network.v1.Interface.DNSConfig:type_name -> siemens.iedge.dmapi.network.v1.Interface.Dns
	9,  // 2: siemens.iedge.dmapi.network.v1.Interface.L2Conf:type_name -> siemens.iedge.dmapi.network.v1.Interface.L2
	10, // 3: siemens.iedge.dmapi.network.v1.Interface.Routes:type_name -> siemens.iedge.dmapi.network.v1.Interface.Route
	0,  // 4: siemens.iedge.dmapi.network.v1.Interface.InterfaceType:type_name -> siemens.iedge.dmapi.network.v1.Interface.InterfaceTypeEnum
	11, // 5: siemens.iedge.dmapi.network.v1.Interface.GsmConfiguration:type_name -> siemens.iedge.dmapi.network.v1.Interface.GsmConf
	1,  // 6: siemens.iedge.dmapi.network.v1.ConnectionSettings.connection_type:type_name -> siemens.iedge.dmapi.network.v1.ConnectionSettings.ConnectionType
	11, // 7: siemens.iedge.dmapi.network.v1.ConnectionSettings.gsm:type_name -> siemens.iedge.dmapi.network.v1.Interface.GsmConf
	4,  // 8: siemens.iedge.dmapi.network.v1.NetworkSettings.Interfaces:type_name -> siemens.iedge.dmapi.network.v1.Interface
	13, // 9: siemens.iedge.dmapi.network.v1.NetworkSettings.LabelMap:type_name -> siemens.iedge.dmapi.network.v1.NetworkSettings.LabelMapEntry
	12, // 10: siemens.iedge.dmapi.network.v1.Interface.L2.AuxiliaryAddresses:type_name -> siemens.iedge.dmapi.network.v1.Interface.L2.AuxiliaryAddressesEntry
	14, // 11: siemens.iedge.dmapi.network.v1.NetworkService.GetAllInterfaces:input_type -> google.protobuf.Empty
	2,  // 12: siemens.iedge.dmapi.network.v1.NetworkService.GetInterfaceWithMac:input_type -> siemens.iedge.dmapi.network.v1.NetworkInterfaceRequest
	3,  // 13: siemens.iedge.dmapi.network.v1.NetworkService.GetInterfaceWithLabel:input_type -> siemens.iedge.dmapi.network.v1.NetworkInterfaceRequestWithLabel
	6,  // 14: siemens.iedge.dmapi.network.v1.NetworkService.ApplySettings:input_type -> siemens.iedge.dmapi.network.v1.NetworkSettings
	5,  // 15: siemens.iedge.dmapi.network.v1.NetworkService.CreateConnection:input_type -> siemens.iedge.dmapi.network.v1.ConnectionSettings
	5,  // 16: siemens.iedge.dmapi.network.v1.NetworkService.RemoveConnection:input_type -> siemens.iedge.dmapi.network.v1.ConnectionSettings
	6,  // 17: siemens.iedge.dmapi.network.v1.NetworkService.GetAllInterfaces:output_type -> siemens.iedge.dmapi.network.v1.NetworkSettings
	4,  // 18: siemens.iedge.dmapi.network.v1.NetworkService.GetInterfaceWithMac:output_type -> siemens.iedge.dmapi.network.v1.Interface
	4,  // 19: siemens.iedge.dmapi.network.v1.NetworkService.GetInterfaceWithLabel:output_type -> siemens.iedge.dmapi.network.v1.Interface
	14, // 20: siemens.iedge.dmapi.network.v1.NetworkService.ApplySettings:output_type -> google.protobuf.Empty
	14, // 21: siemens.iedge.dmapi.network.v1.NetworkService.CreateConnection:output_type -> google.protobuf.Empty
	14, // 22: siemens.iedge.dmapi.network.v1.NetworkService.RemoveConnection:output_type -> google.protobuf.Empty
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_Network_proto_init() }
func file_Network_proto_init() {
	if File_Network_proto != nil {
		return
	}
	file_Network_proto_msgTypes[2].OneofWrappers = []any{}
	file_Network_proto_msgTypes[3].OneofWrappers = []any{
		(*ConnectionSettings_Gsm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Network_proto_rawDesc), len(file_Network_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Network_proto_goTypes,
		DependencyIndexes: file_Network_proto_depIdxs,
		EnumInfos:         file_Network_proto_enumTypes,
		MessageInfos:      file_Network_proto_msgTypes,
	}.Build()
	File_Network_proto = out.File
	file_Network_proto_goTypes = nil
	file_Network_proto_depIdxs = nil
}
